### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by trixn86** [xxhomey19/use-undo#1]
- Mutating objects in the current state should be avoided:

``` javascript
switch (action.type) {
    case UNDO:
      const previous = past.pop(); // this line mutates the current state
      return {
        past,
        present: previous,
        future: [present, ...future],
      };
```

- Handlers should be created with the `useCallback` hook to prevent re-creation of the callback on every render:

E.g. instead of 

``` javascript
const set = newPresent => dispatch({ type: SET, newPresent });
```
you could do this
``` javascript
const set = useCallback(newPresent => dispatch({ type: SET, newPresent }), [dispatch]);
```

**Comment by xxhomey19** [comment]
Thanks for the suggestion!

- Mutating objects in the current state should be avoided
It's meant to mutate the `past`, but it will better if I use an immutable way to replace `pop()`. Like `past.slice(0, -1)`.
- Handlers should be created with the useCallback hook
This is a perfect suggestion!
